### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ddiakopoulos** [KnairdA/boltzbub#1]
Hi @KnairdA - I curate a small [Twitter feed](https://twitter.com/non_manifold) of interesting open-source projects in 3D, AR/VR, geometry, etc. I'd love to post this repo (and your associated blog article) but it would be great to get an explicit license listed in the repo (MIT, Public Domain, etc). Thank you for your great work!

**Comment by KnairdA** [comment]
Sure thing! Thanks for the reminder - I usually release all my code under the MIT license.
